### ISSUE TITLE
Variables that do not match

### ISSUE THREAD

**Issue by zixichen007115** [Emanuele-n/SoRoPCC#1]
If one chooses 'Task-space position regulation' in 'parameters.m,' variable _tip_d_ instead of _qd_ will be generated. But if Feedback for regulation controller is chosen in 'sim_FF_FB_sc.m,' _qd_ is required.

**Comment by em-ni** [comment]
Hello, the problem was that for now 'sim_FF_FB_sc.m' does not provide controllers for task space regulation or tracking (that is what the "sc" in the name stands for). I added the modified file here on GitHub in place of doing a new Release so you can copy and paste it for now. In the next months, I hope to do a big update in a new Release.
Thanks for reporting

**Comment by em-ni** [comment]
sc = shape control (or configuration space)
ts = task space

**Comment by zixichen007115** [comment]
Thank you for your comments. I am looking forward to the update.
